# Step In Data Cleaning

A practical, step-by-step workflow you can follow every time you load a CSV. This is structured the way data analysts especially  and engineers actually approach datasets.

- 1. Load and Inspect the Data
- 2. Understand the Data (Profiling Mindset Of Analyst or Engineer)
- 3. Data Cleaning
- 4. Validate Clean Data
- 5. Save Clean Dataset

### 1. Load and Inspect the Data

i will be importing my csv file from my local machine into jupyter notebook with the aid of pandas and also get to read the csv file

In [1]:
# importing the necessary libaray 

import pandas as pd


df = pd.read_csv(r"C:\Users\HP\Documents\Air-traffic-landings-statistics.csv")

df

,Date,Year,Month,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Landing Aircraft Type,Aircraft Body Type,Aircraft Manufacturer,Aircraft Model,Landing Count,Total Landed Weight
0,9/1/2018,2018,9,SkyWest Airlines,OO,United Airlines,UA,International,Canada,Passenger,Regional Jet,Bombardier,CRJ2,30,1410000
1,9/1/2018,2018,9,Air Canada,AC,Air Canada,AC,International,Canada,Passenger,Narrow Body,Airbus,A320,125,17787978
2,9/1/2018,2018,9,Japan Airlines,JL,Japan Airlines,JL,International,Asia,Passenger,Wide Body,Boeing,B773,30,16620000
3,9/1/2018,2018,9,"COPA Airlines, Inc.",CM,"COPA Airlines, Inc.",CM,International,Central America,Passenger,Narrow Body,Boeing,B739,3,491700
4,9/1/2018,2018,9,Hong Kong Airlines Limited,HX,Hong Kong Airlines Limited,HX,International,Asia,Passenger,Wide Body,Airbus,A359,16,7301712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22042,7/1/2005,2005,7,SkyWest Airlines,OO,Delta Air Lines,DL,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ,155,7285000
22043,7/1/2005,2005,7,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ,268,17956000
22044,7/1/2005,2005,7,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,International,Canada,Passenger,Regional Jet,Bombardier,CRJ,62,4154000
22045,7/1/2005,2005,7,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ,1360,63920000
22046,7/1/2005,2005,7,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Turbo Prop,Embraer,ERJ,1655,42699000


From our imported dataset, we can see we have 22,047 rows and 15 columns. but for demonstration purpose we are going to check the head(first 5 rows) and tail(last 5 rows) of our dataset for future reference or any beginner going through this notebook in my Github repository

### Preview the Data

The aim of this part of the Data previewing process:

- See structure
  
- Understand columns

- Spot obvious issues

In [2]:
# To preview our data frame or table first five rows of our dataset using .head()

df.head()

,Date,Year,Month,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Landing Aircraft Type,Aircraft Body Type,Aircraft Manufacturer,Aircraft Model,Landing Count,Total Landed Weight
0,9/1/2018,2018,9,SkyWest Airlines,OO,United Airlines,UA,International,Canada,Passenger,Regional Jet,Bombardier,CRJ2,30,1410000
1,9/1/2018,2018,9,Air Canada,AC,Air Canada,AC,International,Canada,Passenger,Narrow Body,Airbus,A320,125,17787978
2,9/1/2018,2018,9,Japan Airlines,JL,Japan Airlines,JL,International,Asia,Passenger,Wide Body,Boeing,B773,30,16620000
3,9/1/2018,2018,9,"COPA Airlines, Inc.",CM,"COPA Airlines, Inc.",CM,International,Central America,Passenger,Narrow Body,Boeing,B739,3,491700
4,9/1/2018,2018,9,Hong Kong Airlines Limited,HX,Hong Kong Airlines Limited,HX,International,Asia,Passenger,Wide Body,Airbus,A359,16,7301712

In [3]:
# To preview our data frame or table last five rows of our dataset using .tail()

df.tail()

,Date,Year,Month,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Landing Aircraft Type,Aircraft Body Type,Aircraft Manufacturer,Aircraft Model,Landing Count,Total Landed Weight
22042,7/1/2005,2005,7,SkyWest Airlines,OO,Delta Air Lines,DL,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ,155,7285000
22043,7/1/2005,2005,7,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ,268,17956000
22044,7/1/2005,2005,7,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,International,Canada,Passenger,Regional Jet,Bombardier,CRJ,62,4154000
22045,7/1/2005,2005,7,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ,1360,63920000
22046,7/1/2005,2005,7,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Turbo Prop,Embraer,ERJ,1655,42699000

### Check Shape of our dataset

The aim of this part of the data previewing process tell us:

- Number of rows

- Number of columns

In [4]:
# to check the numbers of rows and column of our dataset using .shape

df.shape

(22047, 15)

### checking column names

The aim of this Data previewing process to check for:

- messy names

- spaces

- inconsistent casing

In [5]:
# to check the dataset columns use .columns

df.columns

Index(['Date', 'Year', 'Month', 'Operating Airline',
       'Operating Airline IATA Code', 'Published Airline',
       'Published Airline IATA Code', 'GEO Summary', 'GEO Region',
       'Landing Aircraft Type', 'Aircraft Body Type', 'Aircraft Manufacturer',
       'Aircraft Model', 'Landing Count', 'Total Landed Weight'],
      dtype='object')

### Check Data Types

The aim of this data previewing process is to know about:

- numeric vs object

- missing values

- memory usage

In [6]:
# To  get the overview of our data 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22047 entries, 0 to 22046
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         22047 non-null  object
 1   Year                         22047 non-null  int64
 2   Month                        22047 non-null  int64
 3   Operating Airline            22047 non-null  object
 4   Operating Airline IATA Code  21972 non-null  object
 5   Published Airline            22047 non-null  object
 6   Published Airline IATA Code  21972 non-null  object
 7   GEO Summary                  22047 non-null  object
 8   GEO Region                   22047 non-null  object
 9   Landing Aircraft Type        22047 non-null  object
 10  Aircraft Body Type           22047 non-null  object
 11  Aircraft Manufacturer        22036 non-null  object
 12  Aircraft Model               22047 non-null  object
 13  Landing Count                22047 non-null  int64
 14  Total Landed Weight          22047 non-null  int64
dtypes: int64(4), object(11)
memory usage: 2.5+ MB

### Summary Statistics

The aim of this data previewing process is  understand the summary statistics of all numerical column:

- mean

- min/max

- distribution insight

In [7]:
df.describe()

               Year         Month  Landing Count  Total Landed Weight
count  22047.000000  22047.000000   22047.000000         2.204700e+04
mean    2011.841475      6.544337     113.382229         1.898969e+07
std        3.886598      3.411153     249.627844         3.033202e+07
min     2005.000000      1.000000       1.000000         6.850000e+03
25%     2008.000000      4.000000      14.000000         3.030457e+06
50%     2012.000000      7.000000      31.000000         9.659716e+06
75%     2015.000000      9.000000      83.000000         1.953000e+07
max     2018.000000     12.000000    2245.000000         2.730420e+08

### Standardize Column Names

The dataset column is in a snake case in most time we can get errorin our code from incosistent column name. its adviseable we conver it to lowercase using:

- .str.strip() → removes extra spaces

- .str.lower() → converts everything to lowercase

- .str.replace(" ", "_") → replaces spaces with underscores

After we run the code the columns are:

- consistent
- easier to type
- production-ready

This avoids errors like:
- df["Operating Airline"]   ❌
- df["operating_airline"]   ✅

In [8]:
df.columns=df.columns.str.strip().str.lower().str.replace(" ","_")
df.columns

Index(['date', 'year', 'month', 'operating_airline',
       'operating_airline_iata_code', 'published_airline',
       'published_airline_iata_code', 'geo_summary', 'geo_region',
       'landing_aircraft_type', 'aircraft_body_type', 'aircraft_manufacturer',
       'aircraft_model', 'landing_count', 'total_landed_weight'],
      dtype='object')

#### Fix Date Column (CRITICAL & Very Important)

converting the date data type from object(str) to datetime data type using:

- .loc[row_indexer, column_indexer]
- : means "all rows"
- "date" is the column

This conversion helps for :

- time filtering
- resampling
- rolling analysis

Without this, time series analysis is impossible.

In [9]:
df.loc[:, "date"] = pd.to_datetime(df["date"])
df["date"].dtype

dtype('O')

## Understand the Data (Profiling Mindset of Analyst or Engineer)

- Check Missing Values
- Check Duplicates
- Inspect Unique Values
- Sort to Detect Outliers

### checking for missing value

Now we want to understand the data and the aim of this is to profile the data

**Ask:**

- Which columns have missing data?

- How much data is missing?

In [10]:
df.isnull().sum()

date                            0
year                            0
month                           0
operating_airline               0
operating_airline_iata_code    75
published_airline               0
published_airline_iata_code    75
geo_summary                     0
geo_region                      0
landing_aircraft_type           0
aircraft_body_type              0
aircraft_manufacturer          11
aircraft_model                  0
landing_count                   0
total_landed_weight             0
dtype: int64

we can now verify that our dataset has 3 columns with missing values, which are listed below:

- operating_airline_iata_code    75
- published_airline_iata_code    75
- aircraft_manufacturer          11

instead of dropping the column with a missing values we are going to fill it with "na or unknown" and the reason for it:

- it preserve data
- it avoid bias
- it keep dataset size intact

In [25]:
df.loc[:, "operating_airline_iata_code"] = df["operating_airline_iata_code"].fillna("unknown")
df.loc[:, "published_airline_iata_code"] = df["published_airline_iata_code"].fillna("unknown")
df.loc[:, "aircraft_manufacturer"] = df["aircraft_manufacturer"].fillna("unknown")

### Check duplicated Values

In [11]:
#### we check for duplicate on our dataset to be sure its consistent

df.duplicated () .sum()

np.int64(11)

In [27]:
# we have 11 duplicates on our data Keeping them would double-count data

df = df.drop_duplicates()

### Inspect Unique Values Useful for:

- categorical columns

- spotting inconsistencies

In [28]:
# validating to show if our dataset still have duplicates values

df.duplicated () .sum()

np.int64(0)

In [30]:
df = df.reset_index(drop=True)
df.index

RangeIndex(start=0, stop=21962, step=1)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21962 entries, 0 to 21961
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   date                         21961 non-null  datetime64[ns]
 1   year                         21961 non-null  float64
 2   month                        21961 non-null  float64
 3   operating_airline            21961 non-null  object
 4   operating_airline_iata_code  21962 non-null  object
 5   published_airline            21961 non-null  object
 6   published_airline_iata_code  21962 non-null  object
 7   geo_summary                  21961 non-null  object
 8   geo_region                   21961 non-null  object
 9   landing_aircraft_type        21961 non-null  object
 10  aircraft_body_type           21961 non-null  object
 11  aircraft_manufacturer        21962 non-null  object
 12  aircraft_model               21961 non-null  object
 13  landing_count                21961 non-null  float64
 14  total_landed_weight          21961 non-null  float64
dtypes: datetime64[ns](1), float64(4), object(10)
memory usage: 2.5+ MB

### Sort to Detect Outliers Look for:

- extreme values

- impossible numbers

### Check Outliers

checking outliers in the dataset using a numerical column in our dataframe:

- landing_count
- total_landed_weight

In [35]:
df.sort_values(by="landing_count", ascending=False).head()

,date,year,month,operating_airline,operating_airline_iata_code,published_airline,published_airline_iata_code,geo_summary,geo_region,landing_aircraft_type,aircraft_body_type,aircraft_manufacturer,aircraft_model,landing_count,total_landed_weight
18627,2007-08-01,2007.0,8.0,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Turbo Prop,Embraer,ERJ,2245.0,57921000.0
18751,2007-07-01,2007.0,7.0,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Turbo Prop,Embraer,ERJ,2192.0,56553600.0
18404,2007-10-01,2007.0,10.0,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Turbo Prop,Embraer,ERJ,2156.0,55624800.0
17145,2008-07-01,2008.0,7.0,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Turbo Prop,Embraer,ERJ,2154.0,55573200.0
16969,2008-08-01,2008.0,8.0,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Turbo Prop,Embraer,EMB,2141.0,55237800.0

In [36]:
df.sort_values(by="total_landed_weight", ascending=False).head()

,date,year,month,operating_airline,operating_airline_iata_code,published_airline,published_airline_iata_code,geo_summary,geo_region,landing_aircraft_type,aircraft_body_type,aircraft_manufacturer,aircraft_model,landing_count,total_landed_weight
21228,2005-12-01,2005.0,12.0,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Narrow Body,Boeing,757,1379.0,273042000.0
20677,2006-04-01,2006.0,4.0,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Narrow Body,Boeing,757,1362.0,269676000.0
10772,2012-07-01,2012.0,7.0,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Narrow Body,Boeing,757,1350.0,267300000.0
12451,2011-06-01,2011.0,6.0,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Narrow Body,Boeing,757,1336.0,264528000.0
21711,2005-08-01,2005.0,8.0,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Narrow Body,Boeing,757,1332.0,263736000.0

In [38]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21962 entries, 0 to 21961
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   date                         21961 non-null  datetime64[ns]
 1   year                         21961 non-null  float64
 2   month                        21961 non-null  float64
 3   operating_airline            21961 non-null  object
 4   operating_airline_iata_code  21962 non-null  object
 5   published_airline            21961 non-null  object
 6   published_airline_iata_code  21962 non-null  object
 7   geo_summary                  21961 non-null  object
 8   geo_region                   21961 non-null  object
 9   landing_aircraft_type        21961 non-null  object
 10  aircraft_body_type           21961 non-null  object
 11  aircraft_manufacturer        21962 non-null  object
 12  aircraft_model               21961 non-null  object
 13  landing_count                21962 non-null  float64
 14  total_landed_weight          21961 non-null  float64
dtypes: datetime64[ns](1), float64(4), object(10)
memory usage: 2.5+ MB

,date,year,month,landing_count,total_landed_weight
count,21961,21961.000000,21961.000000,21962.000000,2.196100e+04
mean,2012-04-19 11:00:09.999544576,2011.838486,6.545012,113.805846,1.905937e+07
min,2005-07-01 00:00:00,2005.000000,1.000000,0.000000,6.850000e+03
25%,2008-12-01 00:00:00,2008.000000,4.000000,14.000000,3.100000e+06
50%,2012-06-01 00:00:00,2012.000000,7.000000,31.000000,9.752600e+06
75%,2015-10-01 00:00:00,2015.000000,9.000000,83.000000,1.953000e+07
max,2018-09-01 00:00:00,2018.000000,12.000000,2245.000000,2.730420e+08
std,NaN,3.889925,3.411513,250.017061,3.037064e+07

### Saving A Clean Dataset 

After your data cleaning processess its always a good norm to save the transfomative dataset to your desireable location as its can be helpful when you need to do an explorative data analysis or anything you need to do with the data.

To save your clean dataset in pandas you to:

- import os (operating system)

- Create the datasets directory if it doesn't exist

- save it to the directory you created

- or you can save it from the path where you read(import) the file from the beginning

In [42]:
import os

# Create the datasets directory if it doesn't exist
if not os.path.exists("datasets"):
    os.makedirs("datasets")
    
# Save our clean data
df.to_csv("datasets/cleaned_air_traffic_2026.csv", index=False)

In [44]:
# Save our clean data to the same directory as the original file where its was read(import)
df.to_csv(r"C:\Users\HP\Documents\cleaned_air_traffic_2026.csv", index=False)